### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by josefelippe45** [amitsingh-007/webpack-watch-external-files-plugin#1]
I've been trying to use the plugin but I keep getting `Cannot read property 'tap' of undefined`

I'm using the plugin this way:
`new WatchExternalFilesPlugin({
          files: ['directory/**/*.js'],
})`

**Comment by adrien-febvay** [comment]
A year old issue... Is this package unattended now?

Anyway, this error shows when `webpack` is outdated. Try installing version 5:
```
npm install the-package@5
```

**Comment by amitsingh-007** [comment]
Hi, sorry for not replying. I don't get much time these days to maintain my open-source work.

This plugin was inspired by [this plugin](https://www.npmjs.com/package/webpack-watch-files-plugin) which didn't support Webpack 5 at that time. I am not sure if it still supports it, but I will mention in the readme that it only supports Webpack 5 and above. And maybe add it as a peer dependency also when I get time.

**Comment by amitsingh-007** [comment]
@josefelippe45 Can you let me know which Webpack version were you using at that time?

**Comment by josefelippe45** [comment]
Hi, thanks for the reply!!!

Unfortunately, I don't have these info anymore... I got along with another solution!

Thanks anyway!
